AddTextEntry("WEAPON_RESONANT", "RESONANT")
AddTextEntry("WEAPON_FAMAS", "FAMAS")
AddTextEntry("WEAPON_DRAGUNOV", "DRAGUNOV")
AddTextEntry("WEAPON_BIZON", "BIZON")
AddTextEntry("WEAPON_AN94", "AN94")
AddTextEntry("WEAPON_ASVAL", "ASVAL")
AddTextEntry("WEAPON_ORIGIN", "ORIGIN")
AddTextEntry("WEAPON_FEN", "FEN")
AddTextEntry("WEAPON_SMG45", "SMG45")
AddTextEntry("WEAPON_50LS", "50LS")
AddTextEntry("WEAPON_GALIL", "GALIL")
AddTextEntry("WEAPON_MP7", "MP7")
AddTextEntry("WEAPON_340", "340")
AddTextEntry("WEAPON_UMP", "UMP")
AddTextEntry("WEAPON_AUG", "AUG")
AddTextEntry("WEAPON_GROZA", "GROZA")
AddTextEntry("WEAPON_CZ9", "CZ9")
AddTextEntry("WEAPON_FLF57", "FLF57")
AddTextEntry("WEAPON_MP5K", "MP5K")
AddTextEntry("WEAPON_G36", "G36")
AddTextEntry("WEAPON_9MMLS", "9MMLS")
AddTextEntry("WEAPON_ATR", "ATR")
AddTextEntry("WEAPON_REG700", "REG700")
AddTextEntry("WEAPON_TKNIFE", "TKNIFE")


